### Login
POST {{server_url}}/login
Content-Type: 'application/json'

{
    "username": "user1",
    "password": "password"
}

> {%
    client.global.set("auth_token", response.body.tokenId);
%}
###

### Get Users
GET {{server_url}}/users?id=asdfafa
Accept: 'text/json'
Authorization: {{auth_token}}

###

### PUT
PUT {{server_url}}/users
Authorization: {{auth_token}}
Content-Type: 'application/json'

{
  "age": 45,
  "email": "user45@example.com",
  "name": "user45",
  "workingPosition": 3
}

###
### Get Users by name
GET {{server_url}}/users?name=user
Accept: 'text/json'
Authorization: {{auth_token}}

###

### delete
DELETE {{server_url}}/users?id=6r8eb1ufw46
Accept: 'text/json'
Authorization: {{auth_token}}
###
