### Login
POST {{server_url}}/login
Content-Type: 'application/json'

{
    "username": "user1",
    "password": "password"
}
###

### Get Users
GET {{server_url}}/users?id=asdfafa
Accept: 'text/json'
Authorization: fdinung34vv
###
